version: '3'

services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web
    networks:
      - my-network

  web:
    build: . 
    volumes:
      - "./:/var/www/html"
    ports:
      - "9000:9000"
    working_dir: "/var/www/html"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      timeout: 10s
    networks:
      - my-network

networks:
  my-network:

