FROM php:7.4-fpm-alpine

RUN apk update && apk add nginx util-linux

COPY nginx.conf /etc/nginx/nginx.conf
COPY php-fpm.conf /usr/local/etc/php-fpm.conf
COPY www.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www/html

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir /secret
COPY index.php .

CMD ["/bin/sh", "/entrypoint.sh"]
